name: Lint and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - uses: pre-commit/action@v3.0.1
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip
      - name: Install Python dependencies
        run: |-
          pip install uv
          uv pip install --system -e ".[dev]"
      - run: refurb chemistryinductivebias
      - run: pylint chemistryinductivebias
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip
      - name: Install Python dependencies
        run: |-
          pip install uv
          uv pip install --system -e ".[dev]"
      - run: pytest chemistryinductivebias/tests
